### ISSUE TITLE
Code too large

### ISSUE THREAD

**Issue by manticore-projects** [javacc/javacc#297]
Greetings!

We finally hit the `Code too large problem` when the Grammar became too large. Please see https://github.com/JSQLParser/JSqlParser/discussions/2161

What is the official advised and guidance on that? How to work around or avoid this challenge please

**Comment by MarcMazas** [comment]
I'm taking a look at it.

**Comment by MarcMazas** [comment]
I made a test with version 8 on the indicated repo and I don't get the "code too large" error. The token manager is different than v7's one (it is table driven).
See my comments in your project's issue.

**Comment by manticore-projects** [comment]
Thank you, we will try JavaCC 8 then.

**Comment by manticore-projects** [comment]
Greetings. I am finally forced taking this serious since our Grammar won't accept any more tokens.

1) I have managed to get JavaCC 8.0.1 running (although documentation is horrible and really stands in the way of a keen adoption)
2) good news: JavaCC 8.0.1 indeed fixes my most pressing issue: too many token/complex token logic and I am able to build the Parser

However, there are caveats:

3) if a custom `SimpleCharStream` has been used before, it will need to rebuild from the provided template:

- apply option `USER_CHAR_STREAM = false;`
- then copy the generated `SimpleCharStream.java` to your sources and incorporate your extension 

4) Token manipulation does not work anymore, because of `input_stream.backup`?!

```
| < S_QUOTED_IDENTIFIER: ( "[" (~["\n","\r","]"])* "]" ) >
    {
        if ( matchedToken.image.charAt(0) == '[' ) {
            matchedToken.image = "[";
            for (int i=0;i<CCJSqlParserConstants.tokenImage.length;i++) {
                if (CCJSqlParserConstants.tokenImage[i].equals("\"[\"")) {
                    matchedToken.kind = i;
                }
            }
            input_stream.backup(image.length() - 1);
        }
    }
```

How can I achieve such manipulations in Java 8 please?

**Comment by manticore-projects** [comment]
I have created a JavaCC-8 based branch of JSQLParser: https://github.com/JSQLParser/JSqlParser/tree/javacc8

Everything seems to work, except those two Token manipulations.
Any help on this will be much appreciated!

**Comment by MarcMazas** [comment]
I have managed to get JavaCC 8.0.1 running: good to here this
although documentation is horrible and really stands in the way of a keen adoption : I made substantial changes in v8.1.0 (committed but not released) : see javacc/javacc-8/docs: could you please tell us in what is lacking?

**Comment by MarcMazas** [comment]
About the CharStream caveat: is there something that we could improve? Or is it just that the API has changed a little but this is not advertised?

**Comment by MarcMazas** [comment]
About token manipulation that does not work anymore: I understand the code you are showing is your old code for javacc v7, that does not do the same with javacc v8: right? I'll look at it. May be image does not point to the same thing as before.

These Two Token manipulations: what is the second one?

**Comment by manticore-projects** [comment]
> I made substantial changes in v8.1.0 (committed but not released) : see javacc/javacc-8/docs: could you please tell us in what is lacking?

I do appreciate your work a lot though I want to offer some perspective:
1) JavaCC-7 suddenly stops working because of the token manager
2) so I need to find a solution quick
3) try to switch to JavaCC-8
4) JavaCC-8 Readme on GitHub is pretty useless, no build instructions
5) cloning from GitHub gives me sources that don't compile
6) Maven Central point me to 8.0.6 that seems to be dead though?
7) only after digging deep and reading across various issues and discussions, I can make a 8.0.1 work -- which is from  2022!

Nothing of this encourages my faith in JavaCC-8.
I know that all of this is voluntary work and I have no right to complain. Instead I would like to help with critical feedback speeding up the adoption and gaining the critical mass.

So maybe we can:

1) Cleanup the Github Repo and the Maven Repo (deleting all garbage)
2) Put the JavaCC 9 sources into a state, where it compiles (`mvn install` works)
3) Update the GitHub README with clear instructions how to download and/or compile as well as what adjustments are needed
4) then point on the verbose documentation in the README.
5) optionally: release any newer Snapshot of JavaCC 8 as a sign of life

Like explaining JavaCC 8 adoption to a 4 year old child.

I will happily sign up for tasks 3) and 4) above (since I got it running).

**Comment by manticore-projects** [comment]
> About the CharStream caveat: is there something that we could improve? Or is it just that the API has changed a little but this is not advertised?

At JSQLParser we have had an ancient customized implementation of `SimpleCharStream` and it suddenly threw "index out of bounds" errors with JavaCC 8.

I fixed that by generating `SimpleCharStream`  afresh with JavaCC 8 and then incorporated our customization.

This has worked well and maybe should be mentioned as an optional migration step.
Similar to renaming `SimpleNode` into `Node`.

**Comment by manticore-projects** [comment]
> About token manipulation that does not work anymore: I understand the code you are showing is your old code for javacc v7, that does not do the same with javacc v8: right? 

Correct.

> I'll look at it. May be image does not point to the same thing as before.

Any help or hint will be much appreciated and also should go into a `Migration Guide`.
Although I am in the process of refactoring those token manipulations completely, using Productions and JAVA_CODE instead.

> These Two Token manipulations: what is the second one?

The second one is very similar to the first one, just much more complex. Please ignore it for the moment because once we get the first one working, I will know what to do with the second one.

(Also, I am rewriting this stuff -- Token manipulation was ugly from  start.)

**Comment by manticore-projects** [comment]
And big big thank you for helping!
We could make JSQLParser the guinea pig and prime grammar for JavaCC 8 together. You will have my full support of course.

Right now, 88 out of 2,000 test are failing -- most obscure and exotic stuff.

**Comment by MarcMazas** [comment]
>     4. JavaCC-8 Readme on GitHub is pretty useless, no build instructions
Well, have you seen : https://github.com/javacc/javacc-8/tree/release / Getting Started / Rebuilding JavaCC which shows See README_BUILD.md which has a Local build process section.
 
>     5. cloning from GitHub gives me sources that don't compile
Can you send me the corresponding elements?
 
>     6. Maven Central point me to 8.0.6 that seems to be dead though?
Yes, and as indicated I have not yet release 8.1.0
 
 
> Nothing of this encourages my faith in JavaCC-8. I know that all of this is voluntary work and I have no right to complain. Instead I would like to help with critical feedback speeding up the adoption and gaining the critical mass.
> 
> So maybe we can:
> 
>     1. Cleanup the Github Repo and the Maven Repo (deleting all garbage)
IMHO I think I have made a big laundry pass on the different javacc-8 repos...
Once I release  v8.1.0 will I need to delete old versions in Maven repos?

>     2. Put the JavaCC 9 sources into a state, where it compiles (`mvn install` works)
Tell me what goes wrond (see https://github.com/javacc/javacc-8/blob/release/README_BUILD.md#local-build-process)
 
>     3. Update the GitHub README with clear instructions how to download and/or compile as well as what adjustments are needed
Same as above.
I'll add a migration section.
 
>     4. then point on the verbose documentation in the README.
?
 
> I will happily sign up for tasks 3) and 4) above (since I got it running).
OK!

**Comment by MarcMazas** [comment]
> > About the CharStream caveat: is there something that we could improve? Or is it just that the API has changed a little but this is not advertised?
> 
> At JSQLParser we have had an ancient customized implementation of `SimpleCharStream` and it suddenly threw "index out of bounds" errors with JavaCC 8.
> 
> I fixed that by generating `SimpleCharStream` afresh with JavaCC 8 and then incorporated our customization.
> 
> This has worked well and maybe should be mentioned as an optional migration step. Similar to renaming `SimpleNode` into `Node`.

Thanks, noticed.

**Comment by MarcMazas** [comment]
> > About token manipulation that does not work anymore: I understand the code you are showing is your old code for javacc v7, that does not do the same with javacc v8: right?
> 
> Correct.
> 
> > I'll look at it. May be image does not point to the same thing as before.

The issue you faced in your <S_CHAR_LITERAL> definition is of the same kink as we have in the VST interpreter in the examples (that I investigated a little a few weeks ago). I made a fix and the error disappeared. I need to make more non regression checks. In essence: a line of code (which updates image) is / was not generated.
 
> Any help or hint will be much appreciated and also should go into a `Migration Guide`. Although I am in the process of refactoring those token manipulations completely, using Productions and JAVA_CODE instead.
> 
> > These Two Token manipulations: what is the second one?
> 
> The second one is very similar to the first one, just much more complex. Please ignore it for the moment because once we get the first one working, I will know what to do with the second one.
> 
> (Also, I am rewriting this stuff -- Token manipulation was ugly from start.)

Current status:

- the LikeExpressionTest error disappeared

- some errors come from the fact that the ParseException error message has changed (e.g. in CreateViewTest): instead of starting with "Encountered unexpected token", now it is "Encountered: <kind / image / label>.... Was expecting: ..."; this message can be customized in the ParseException.template, or you just change the expected message in the test.

- the javacc compilation of your grammar adds new warnings on string literal tokens that cannot be matched (like "KILL SESSION" that will be matched by <S_IDENTIFIER>), and some tests fail because of this (you should declare "KILL" and "SESSION" as keywords tokens like the other keywords); I don't know exactly why this does not appear in v7. I suspect this appears now in v8 because of a different flow of processing token definitions. We'll have to state which one of the current or the old processing is the right one.

**Comment by manticore-projects** [comment]
> Can you send me the corresponding elements?

So those are my steps:
```bash
are@archlinux ~/d/src> pwd
/home/are/data/src
are@archlinux ~/d/src> mkdir test
are@archlinux ~/d/src> cd test
are@archlinux ~/d/s/test> git clone git@github.com:javacc/javacc-8.git

are@archlinux ~/d/s/test> cd javacc-8
are@archlinux ~/d/s/t/javacc-8 (release)> git clone git@github.com:javacc/javacc-8-core.git

are@archlinux ~/d/s/t/javacc-8 (release)> git clone git@github.com:javacc/javacc-8-java.git

are@archlinux ~/d/s/t/javacc-8 (release)> mvn clean package
```

Output is:
```[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------------< org:javacc >-----------------------------
[INFO] Building JavaCC 8.1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- clean:3.4.0:clean (default-clean) @ javacc ---
[INFO] 
[INFO] --- help:3.5.1:active-profiles (display-active-profiles) @ javacc ---
[INFO] 
Active Profiles for Project 'org:javacc:pom:8.1.0-SNAPSHOT':

The following profiles are active:




[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.335 s
[INFO] Finished at: 2025-05-06T16:18:26+07:00
[INFO] ------------------------------------------------------------------------
```

As you can see nothing happens, the sub modules are not found or acknowledged.

So I try to compile the subprojects:
```bash
are@archlinux ~/d/s/t/javacc-8 (release)> cd javacc-8-core
are@archlinux ~/d/s/t/j/javacc-8-core (release)> mvn clean package
```

which gives me error:
```[ERROR] Failed to execute goal org.javacc.plugin:javacc-maven-plugin:3.0.3:jjtree-javacc (jjt-jcc) on project core: Execution jjt-jcc of goal org.javacc.plugin:javacc-maven-plugin:3.0.3:jjtree-javacc failed: Plugin org.javacc.plugin:javacc-maven-plugin:3.0.3 or one of its dependencies could not be resolved:
[ERROR] 	Failed to read artifact descriptor for org.javacc.generator:java:jar:8.1.0-SNAPSHOT
```

**Comment by manticore-projects** [comment]
I have tried with both possible project structures:

```
are@archlinux ~/d/s/test> ls
javacc-8/  javacc-8-core/  javacc-8-java/
```

and also
```
are@archlinux ~/d/s/test> ls -d javacc-8/*
javacc-8/docs/           javacc-8/keystore       javacc-8/pom.xml          javacc-8/SECURITY.md
javacc-8/javacc-8-core/  javacc-8/LICENSE        javacc-8/README_BUILD.md
javacc-8/javacc-8-java/  javacc-8/old_but_kept/  javacc-8/README.md
```

**Comment by manticore-projects** [comment]
A very simple chain of re-producible commands would go a long way.
Maybe it was a good idea to split the documentation into one for (JavaCC) developers and one for users.

**Comment by MarcMazas** [comment]
All 3 repos at the same level.
For javacc-8, then javacc-8-core, then javacc-8-java: cd under repo, mvn -X clean install

**Comment by manticore-projects** [comment]
> All 3 repos at the same level. For javacc-8, then javacc-8-core, then javacc-8-java: cd under repo, mvn -X clean install

That is useful information that I could not find anywhere!

So lets try this:

``` bash
are@archlinux ~/d/s/test> ls
javacc-8/  javacc-8-core/  javacc-8-java/

// works!
are@archlinux ~/d/s/test> cd javacc-8
are@archlinux ~/d/s/t/javacc-8 (release)> mvn clean install

// fails!
are@archlinux ~/d/s/t/javacc-8 (release)> cd ../javacc-8-core
are@archlinux ~/d/s/t/javacc-8-core (release)> mvn clean install
```

Output of `javacc-8-core`` is:
```
[ERROR] Failed to execute goal org.javacc.plugin:javacc-maven-plugin:3.0.3:jjtree-javacc (jjt-jcc) on project core: Execution jjt-jcc of goal org.javacc.plugin:javacc-maven-plugin:3.0.3:jjtree-javacc failed: Plugin org.javacc.plugin:javacc-maven-plugin:3.0.3 or one of its dependencies could not be resolved:
[ERROR] 	Failed to read artifact descriptor for org.javacc.generator:java:jar:8.1.0-SNAPSHOT
```

**Comment by MarcMazas** [comment]
Have you run mvn clean install under javacc-8 before?

**Comment by manticore-projects** [comment]
Just for the sake of trying, lets build `javacc-8-java` first:

```bash
are@archlinux ~/d/s/t/javacc-8-core (release) [1]> cd ../javacc-8-java/
are@archlinux ~/d/s/t/javacc-8-java (release)> mvn clean install
```

also fails with
```
[ERROR] /home/are/Documents/src/test/javacc-8-java/src/main/java/org/javacc/java/JJTreeCodeGenerator.java:[520,24] cannot find symbol
  symbol:   variable NUO__PARSER_NAME
  location: class org.javacc.parser.Options
```

**Comment by manticore-projects** [comment]
> Have you run mvn clean install under javacc-8 before?

yes Sir, exactly as shown in the commands above.
I can record a screencast if this helps the analysis.

**Comment by MarcMazas** [comment]
Yes, I see: 8.1.0-SNAPSHOT trying to build itself, needs to be produced by an older version:
workaround: in javacc-8/pom.xml, temp change <version>${javacc.java.version}</version> of org.javacc.generator.java to 8.0.1 for example.
I'll see how to automatically handle both cases (first time / next ones).

**Comment by manticore-projects** [comment]
I apologise for being pain and I know myself how annoying such pesky release and PR work is.

Though my advise was to focus together on something that just works simple, out of the box and via the established channels.

It will help adoption and gaining the critical mass! Right now JavaCC is buried under too much red-tape in my opinion.

'Release earlier, release oftener' is a well established concept -- with many counter examples like KDE 4.0 :-)

**Comment by manticore-projects** [comment]
> workaround: in javacc-8/pom.xml, temp change ${javacc.java.version} of org.javacc.generator.java to 8.0.1 for example.

This is a big improvement and now `javacc-8-core` compiles.
However, `javacc-8-java` still fails (even when skipping tests `-DskipTests`):

```
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  bas01/pom.xml

[ERROR] /home/are/Documents/src/test/javacc-8-java/it/build-utils.xml:87: /home/are/Documents/src/test/javacc-8-java/issues/bas01/files/clc1(.cpy).err does not match /home/are/Documents/src/test/javacc-8-java/issues/bas01/files/clc1.exp_err!
```

I can see `java-8.1.0-SNAPSHOT.jar` in the `target` folder, which is good.
But `mvn install` fails from the error above, so deployment is disrupted.

**Comment by MarcMazas** [comment]
mvn clean install -P!run-its for not running the integration tests.
However why did the bas01 test fail ? In its /issues/bas01/build.log

**Comment by manticore-projects** [comment]
> mvn clean install -P!run-its for not running the integration tests. 

Why not use a simple, well establish `-DskipTests`? 

> However why did the bas01 test fail ? In its /issues/bas01/build.log

```
[ERROR] /home/are/Documents/src/test/javacc-8-java/it/build-utils.xml:87: /home/are/Documents/src/test/javacc-8-java/issues/bas01/files/clc1(.cpy).err does not match /home/are/Documents/src/test/javacc-8-java/issues/bas01/files/clc1.exp_err!

// clc1(.cpy).err does not match clc1.exp_er
```

Integration test files: 

[files.zip](https://github.com/user-attachments/files/20060113/files.zip)

**Comment by manticore-projects** [comment]
So, finally with your valuable help, I have been able to compile and deploy `JavaCC 8.1 Snapshot`, yehaw! I will post a simple reproducer shortly.

Next question, would that not be the perfect opportunity to enable SonaType Snapshot deployment in order to enable any interested party using latest greatest snapshot?

**Comment by MarcMazas** [comment]
Why not the well established -DskipTests? Because the integration tests are (historically) disseminated under issues / examples / grammars with the it umbrella...

Can you share me the bas01/files/clc1.err file?

**Comment by MarcMazas** [comment]
> So, finally with your valuable help, I have been able to compile and deploy `JavaCC 8.1 Snapshot`, yehaw! I will post a simple reproducer shortly.

Can you propose something under README_BUILD.md (of javacc-8)?

> 
> Next question, would that not be the perfect opportunity to enable SonaType Snapshot deployment in order to enable any interested party using latest greatest snapshot?

I'm open to this...

**Comment by manticore-projects** [comment]
> Why not the well established -DskipTests? Because the integration tests are (historically) disseminated under issues / examples / grammars with the it umbrella...

Will this help adoption and acceptance? Was it easier to streamline it or to explain it continuously?
 Its your call of course.

> Can you share me the bas01/files/clc1.err file?

[files.zip](https://github.com/user-attachments/files/20060166/files.zip)

**Comment by manticore-projects** [comment]
> Can you propose something under README_BUILD.md (of javacc-8)?

Sure, I am working on exactly this:
1) a brief `compile from GitHub` section without much ado
2) a `deplay snapshot action` for GitHub

And thanks a lot for your help, merci beaucoups!

**Comment by manticore-projects** [comment]
the following script works reliably for building from GitHub:

```bash
mkdir javacc-8
cd javacc-8

git clone git@github.com:javacc/javacc-8.git
cd javacc-8
sed -i 's|<javacc.java.version>[^<]*</javacc.java.version>|<javacc.java.version>8.0.1</javacc.java.version>|' pom.xml
mvn clean install -P!run-its
cd ..


git clone git@github.com:javacc/javacc-8-core.git
cd javacc-8-core
mvn clean install -P!run-its
cd ..

git clone git@github.com:javacc/javacc-8-java.git
cd javacc-8-java
mvn clean install -P!run-its
cd ..
```

**Comment by MarcMazas** [comment]
[ERROR] /home/are/Documents/src/test/javacc-8-java/it/build-utils.xml:87: /home/are/Documents/src/test/javacc-8-java/issues/bas01/files/clc1(.cpy).err does not match /home/are/Documents/src/test/javacc-8-java/issues/bas01/files/clc1.exp_err!

// clc1(.cpy).err does not match clc1.exp_er

The difference comes from the platform line separator: you are on Unix, and the reference file comes from Windows, and the token traces therefore a a little different. I'll have to work on this.

**Comment by manticore-projects** [comment]
Thanks, I can also help you with Github actions to run all this staff against different OSes, JDKs and Generator targets (Java, JS, CSharp, CPP).

**Comment by MarcMazas** [comment]
There are indeed  GitHub actions for all; the only thing is that as all the tests are not fully ported to csharp / cpp or updated / fixed for java, I have disabled them in the actions.

**Comment by MarcMazas** [comment]
I pushed commits to core & java for the lexical actions; you can fetch them and check that some errors disappeared.

**Comment by manticore-projects** [comment]
> check that some errors disappeared.

Unfortunately nothing has changed, the same quoting related tests are still failing.

**Comment by MarcMazas** [comment]
> Yes, I see: 8.1.0-SNAPSHOT trying to build itself, needs to be produced by an older version: workaround: in javacc-8/pom.xml, temp change ${javacc.java.version} of org.javacc.generator.java to 8.0.1 for example. I'll see how to automatically handle both cases (first time / next ones).

I pushed a commit for handling this case.

**Comment by MarcMazas** [comment]
> > check that some errors disappeared.
> 
> Unfortunately nothing has changed, the same quoting related tests are still failing.

Do you get this in CCJSqlParserTokenManager.java?
```
  void TokenLexicalActions(Token matchedToken) {
    // TOKEN lexical actions
    switch (matchedToken.kind) {
    case 478: {
      lengthOfMatch = jjmatchedPos + 1;
      image.append(input_stream.GetSuffix(jjimageLen + lengthOfMatch));
      if (!configuration.getAsBoolean(Feature.allowBackslashEscapeCharacter)
          && matchedToken.image.contains("\\'")) {
        matchedToken.image = image.substring(0, image.indexOf("\\'") + 1) + "'";
        for (int i = 0; i < CCJSqlParserConstants.tokenImage.length; i++) {
          if (CCJSqlParserConstants.tokenImage[i].equals("<S_CHAR_LITERAL>")) {
            matchedToken.kind = i;
          }
        }
        input_stream.backup(image.length() - matchedToken.image.length());
      } else if (configuration.getAsBoolean(Feature.allowBackslashEscapeCharacter)
          && matchedToken.image.contains("\\''")) {
        matchedToken.image = image.substring(0, image.lastIndexOf("\\'") + 3);
        for (int i = 0; i < CCJSqlParserConstants.tokenImage.length; i++) {
          if (CCJSqlParserConstants.tokenImage[i].equals("<S_CHAR_LITERAL>")) {
            matchedToken.kind = i;
          }
        }
        input_stream.backup(image.length() - matchedToken.image.length());
      }
      break;
    }
    case 479: {
      lengthOfMatch = jjmatchedPos + 1;
      image.append(input_stream.GetSuffix(jjimageLen + lengthOfMatch));
      if (!configuration.getAsBoolean(Feature.allowSquareBracketQuotation)
          && matchedToken.image.charAt(0) == '[') {
        matchedToken.image = "[";
        for (int i = 0; i < CCJSqlParserConstants.tokenImage.length; i++) {
          if (CCJSqlParserConstants.tokenImage[i].equals("\"[\"")) {
            matchedToken.kind = i;
          }
        }
        input_stream.backup(image.length() - 1);
      }
      break;
    }
    default:
      break;
    }
  }
```
You need to fetch from origin, rerun mvn install on core then java, then rebuild your parser.

**Comment by manticore-projects** [comment]
Greetings @MarcMazas!

> I pushed commits to core & java for the lexical actions; you can fetch them and check that some errors disappeared.

This change has had an effect indeed and now the quoting related tests succeed again! I have to disable Gradle caching, pulling/deploying itself was not enough.

We are down to 41 failures out of 3000 tests now!

Although something else broke:
```
// worked before
        (
            <K_DISTINCT> { Distinct distinct = new Distinct(); plainSelect.setDistinct(distinct); }
            [ LOOKAHEAD(2) "ON" "(" distinctOn=SelectItemsList() { plainSelect.getDistinct().setOnSelectItems(distinctOn); } ")" ]
        )
        |
        <K_UNIQUE> { Distinct distinct = new Distinct(true); plainSelect.setDistinct(distinct); }
```

Now I get a complain, that `distinct` was defined already -- which I can work around easily of course.

**Comment by MarcMazas** [comment]
> This change has had an effect indeed and now the quoting related tests succeed again! I have to disable Gradle caching, pulling/deploying itself was not enough.

I don't know much about Gradle: are you pointing that Gradle caches the javacc jars, so that the rebuilt one is not taken in account?
